"""initial persistence schema

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import VECTOR
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("github_owner", sa.String(length=255), nullable=False),
        sa.Column("github_name", sa.String(length=255), nullable=False),
        sa.Column("clone_url", sa.Text(), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("local_status", sa.String(length=50), server_default="pending", nullable=False),
        sa.Column("index_status", sa.String(length=50), server_default="pending", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
    )
    op.create_index(
        "uq_repositories_github_identity",
        "repositories",
        [sa.literal_column("lower(github_owner)"), sa.literal_column("lower(github_name)")],
        unique=True,
    )
    op.create_table(
        "code_chunks",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=100), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding", VECTOR(dim=1536), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "start_line > 0 AND end_line >= start_line",
            name=op.f("ck_code_chunks_valid_line_range"),
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_code_chunks_repository_id_repositories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_code_chunks")),
    )
    op.create_index(
        op.f("ix_code_chunks_content_hash"), "code_chunks", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_code_chunks_repository_id"), "code_chunks", ["repository_id"], unique=False
    )
    op.create_table(
        "issues",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("github_issue_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("state", sa.String(length=50), server_default="open", nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("github_issue_number > 0", name=op.f("ck_issues_positive_issue_number")),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_issues_repository_id_repositories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issues")),
        sa.UniqueConstraint(
            "repository_id", "github_issue_number", name=op.f("uq_issues_repository_id")
        ),
    )
    op.create_index(op.f("ix_issues_repository_id"), "issues", ["repository_id"], unique=False)
    op.create_table(
        "implementation_plans",
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), server_default="draft", nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"], ["issues.id"], name=op.f("fk_implementation_plans_issue_id_issues")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_implementation_plans")),
    )
    op.create_index(
        op.f("ix_implementation_plans_issue_id"), "implementation_plans", ["issue_id"], unique=False
    )
    op.create_table(
        "execution_runs",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), server_default="pending", nullable=False),
        sa.Column("branch_name", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completed_at >= started_at", name=op.f("ck_execution_runs_valid_run_times")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["implementation_plans.id"],
            name=op.f("fk_execution_runs_plan_id_implementation_plans"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_runs")),
    )
    op.create_index(op.f("ix_execution_runs_plan_id"), "execution_runs", ["plan_id"], unique=False)
    op.create_table(
        "plan_tasks",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("task_key", sa.String(length=100), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), server_default="pending", nullable=False),
        sa.Column(
            "dependencies",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "target_files",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("sequence", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(dependencies) = 'array'", name=op.f("ck_plan_tasks_dependencies_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(target_files) = 'array'", name=op.f("ck_plan_tasks_target_files_array")
        ),
        sa.CheckConstraint("sequence >= 0", name=op.f("ck_plan_tasks_nonnegative_sequence")),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["implementation_plans.id"],
            name=op.f("fk_plan_tasks_plan_id_implementation_plans"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_tasks")),
        sa.UniqueConstraint("plan_id", "task_key", name=op.f("uq_plan_tasks_plan_id")),
    )
    op.create_index(op.f("ix_plan_tasks_plan_id"), "plan_tasks", ["plan_id"], unique=False)
    op.create_table(
        "pull_requests",
        sa.Column("execution_run_id", sa.Uuid(), nullable=False),
        sa.Column("github_pr_number", sa.Integer(), nullable=False),
        sa.Column("github_url", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), server_default="open", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "github_pr_number > 0", name=op.f("ck_pull_requests_positive_pr_number")
        ),
        sa.ForeignKeyConstraint(
            ["execution_run_id"],
            ["execution_runs.id"],
            name=op.f("fk_pull_requests_execution_run_id_execution_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pull_requests")),
        sa.UniqueConstraint("execution_run_id", name=op.f("uq_pull_requests_execution_run_id")),
    )
    op.create_table(
        "task_executions",
        sa.Column("execution_run_id", sa.Uuid(), nullable=False),
        sa.Column("plan_task_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), server_default="pending", nullable=False),
        sa.Column("attempt", sa.Integer(), server_default="1", nullable=False),
        sa.Column("output_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt > 0", name=op.f("ck_task_executions_positive_attempt")),
        sa.ForeignKeyConstraint(
            ["execution_run_id"],
            ["execution_runs.id"],
            name=op.f("fk_task_executions_execution_run_id_execution_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_task_id"],
            ["plan_tasks.id"],
            name=op.f("fk_task_executions_plan_task_id_plan_tasks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_executions")),
        sa.UniqueConstraint(
            "execution_run_id",
            "plan_task_id",
            "attempt",
            name=op.f("uq_task_executions_execution_run_id"),
        ),
    )
    op.create_index(
        op.f("ix_task_executions_execution_run_id"),
        "task_executions",
        ["execution_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_executions_plan_task_id"), "task_executions", ["plan_task_id"], unique=False
    )
    op.create_table(
        "agent_runs",
        sa.Column("execution_run_id", sa.Uuid(), nullable=False),
        sa.Column("task_execution_id", sa.Uuid(), nullable=True),
        sa.Column("agent_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), server_default="pending", nullable=False),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column(
            "input_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "output_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(input_metadata) = 'object'",
            name=op.f("ck_agent_runs_input_metadata_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(output_metadata) = 'object'",
            name=op.f("ck_agent_runs_output_metadata_object"),
        ),
        sa.CheckConstraint(
            "completed_at >= started_at", name=op.f("ck_agent_runs_valid_agent_times")
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0 AND cost_usd >= 0",
            name=op.f("ck_agent_runs_nonnegative_usage"),
        ),
        sa.ForeignKeyConstraint(
            ["execution_run_id"],
            ["execution_runs.id"],
            name=op.f("fk_agent_runs_execution_run_id_execution_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["task_execution_id"],
            ["task_executions.id"],
            name=op.f("fk_agent_runs_task_execution_id_task_executions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(
        op.f("ix_agent_runs_execution_run_id"), "agent_runs", ["execution_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_runs_task_execution_id"), "agent_runs", ["task_execution_id"], unique=False
    )
    op.execute("""
        CREATE FUNCTION set_record_updated_at() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            NEW.updated_at = clock_timestamp();
            RETURN NEW;
        END;
        $$
    """)
    for table in (
        "repositories",
        "issues",
        "code_chunks",
        "implementation_plans",
        "plan_tasks",
        "execution_runs",
        "task_executions",
        "agent_runs",
        "pull_requests",
    ):
        op.execute(
            f"CREATE TRIGGER update_timestamp BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION set_record_updated_at()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_runs_task_execution_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_execution_run_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_task_executions_plan_task_id"), table_name="task_executions")
    op.drop_index(op.f("ix_task_executions_execution_run_id"), table_name="task_executions")
    op.drop_table("task_executions")
    op.drop_table("pull_requests")
    op.drop_index(op.f("ix_plan_tasks_plan_id"), table_name="plan_tasks")
    op.drop_table("plan_tasks")
    op.drop_index(op.f("ix_execution_runs_plan_id"), table_name="execution_runs")
    op.drop_table("execution_runs")
    op.drop_index(op.f("ix_implementation_plans_issue_id"), table_name="implementation_plans")
    op.drop_table("implementation_plans")
    op.drop_index(op.f("ix_issues_repository_id"), table_name="issues")
    op.drop_table("issues")
    op.drop_index(op.f("ix_code_chunks_repository_id"), table_name="code_chunks")
    op.drop_index(op.f("ix_code_chunks_content_hash"), table_name="code_chunks")
    op.drop_table("code_chunks")
    op.drop_index("uq_repositories_github_identity", table_name="repositories")
    op.drop_table("repositories")
    op.execute("DROP FUNCTION set_record_updated_at()")
    # Keep vector: it may predate this migration or be shared by other schemas.
    # ### end Alembic commands ###
